### PR TITLE
Feature/brian data file s3 uploader

### PR DESCRIPTION
**Pull request by briandoconnor**
There are a few items still to do on this but I wanted to open the pull request to be a place to collect comments.  Items to do:
* finish running the script to "seed" the bucket with files/tags on files before turning on TravisCI (otherwise the build will fail since it takes a long time to run initially)
* setup the script in TravisCI
* retool the standalone script from Sam to take bucket and path as arguments so it's more generically useful

### CODE REVIEW

**Comment by briandoconnor** [comment]
Need to update the README.md to include information that the script should be manually re-run if there are a lot of data file changes in the data bundles.  Since a slow run of this script will potentially cause TravisCI to timeout.

**Comment by briandoconnor** [comment]
FYI:

sam_pierson [3:25 PM] 
@briandoconnor btw I messed up the tags a tad - it’s `hca-dss-content-type` not `content-type`

briandoconnor [3:28 PM] 
Ahhh!!!  That’s OK.  I’ll let the current process finish over the weekend, update the feature branch, and run it again.  It should give us a good idea of the runtime when in Travis.  I believe your code is written to add tags if they’re missing.  Should this tag be explicitly removed?

[3:29] 
in which case I think the code will need a bit of a tweak to remove tags that aren’t needed.

**Comment by briandoconnor** [comment]
the content type tag issue was addressed

**Comment by kozbo** [comment]
Is this blocked by [#195](https://github.com/HumanCellAtlas/data-store/issues/195)?

**Comment by kozbo** [comment]
not blocked by #195, but large file upload

**Comment by kozbo** [comment]
blocked on #234

**Comment by briandoconnor** [comment]
OK, comparing to branch spierson-stager it looks like Sam has used this branch as a base and changed only his own code.  To move this forward I'm merging here.

**Pull request merged**
